CREATE TABLE electronic_components_test(
    ecid integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ecname varchar2(256) NOT NULL,
    etype integer NOT NULL,
    X integer NOT NULL,
    Y integer NOT NULL,
    voltage_level varchar2(15) NOT NULL
);
ALTER TABLE electronic_components_test ADD(
    constraint ec_pk_test PRIMARY KEY (ecid),
    constraint ec_fk_test FOREIGN KEY (etype) references electronic_components_types_test(cid),
    constraint ec_ck_test CHECK (voltage_level IN ('high voltage', 'medium voltage', 'low voltage')),
    constraint ec_uq_test UNIQUE (ecname)
);