CREATE TABLE electronic_components_types_test(
    cid integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cname varchar2(256) NOT NULL
);
ALTER TABLE electronic_components_types_test
ADD (
    CONSTRAINT ect_pk_test PRIMARY KEY (cid),
    CONSTRAINT ect_uq_test UNIQUE (cname)
);