CREATE TABLE electronic_components(
    ecid integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ecname varchar2(256) NOT NULL,
    etype integer NOT NULL,
    X integer NOT NULL,
    Y integer NOT NULL,
    voltage_level varchar2(15) NOT NULL
);
ALTER TABLE electronic_components ADD(
    constraint ec_pk PRIMARY KEY (ecid),
    constraint ec_fk FOREIGN KEY (etype) references electronic_components_types(cid),
    constraint ec_ck CHECK (voltage_level IN ('high voltage', 'medium voltage', 'low voltage')),
    constraint ec_uq UNIQUE (ecname)
);