CREATE TABLE electronic_components_types(
    cid integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cname varchar2(256) NOT NULL
);
ALTER TABLE electronic_components_types
ADD (
    CONSTRAINT ect_pk PRIMARY KEY (cid),
    CONSTRAINT ect_uq UNIQUE (cname)
);