CREATE TABLE fault_actions(
  faid integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
  date_of_action varchar2(32) NOT NULL,
  adesc varchar(256) NOT NULL,
  fid varchar2(32) NOT NULL
);
ALTER TABLE fault_actions
ADD(
    CONSTRAINT fa_fk FOREIGN KEY (fid) REFERENCES reported_faults(fid),
    CONSTRAINT fa_pk PRIMARY KEY (faid, fid)
);